function [playerName,playerID,plateAppearances,atBats,hitsTotal,hitsDoubles,hitsTriples,homeRuns,sacHits,sacFlies,baseOnBalls,hitByPitch,strikeOuts] = functionImportStats(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [playerName,playerID,plateAppearances,atBats,hitsTotal,hitsDoubles,hitsTriples,homeRuns,sacHits,sacFlies,baseOnBalls,hitByPitch,strikeOuts]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [playerName,playerID,plateAppearances,atBats,hitsTotal,hitsDoubles,hitsTriples,homeRuns,sacHits,sacFlies,baseOnBalls,hitByPitch,strikeOuts]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [playerName,playerID,plateAppearances,atBats,hitsTotal,hitsDoubles,hitsTriples,homeRuns,sacHits,sacFlies,baseOnBalls,hitByPitch,strikeOuts]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [playerName,playerID,plateAppearances,atBats,hitsTotal,hitsDoubles,hitsTriples,homeRuns,sacHits,sacFlies,baseOnBalls,hitByPitch,strikeOuts] = importfile('testStatsAstros.xlsx','Sheet1',2,12);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2017/11/10 16:20:35

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 12;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:M%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:M%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
playerName = cellstr(stringVectors(:,1));
playerID = data(:,1);
plateAppearances = data(:,2);
atBats = data(:,3);
hitsTotal = data(:,4);
hitsDoubles = data(:,5);
hitsTriples = data(:,6);
homeRuns = data(:,7);
sacHits = data(:,8);
sacFlies = data(:,9);
baseOnBalls = data(:,10);
hitByPitch = data(:,11);
strikeOuts = data(:,12);

